export const LOAD_NEWS_SUCCESS = 'LOAD_NEWS_SUCCESS';
export const CATEGORY_SELECTED = 'CATEGORY_SELECTED';
export const PREFERENCES_ADDED = 'PREFERENCES_ADDED';
export const PREFERENCES_DELETED = 'PREFERENCES_DELETED';
export const LOAD_RETRIEVED_NEWS_SUCCESS = 'LOAD_RETRIEVED_NEWS_SUCCESS';